import {
  getPluralDisplayNameForCanonicalKey,
  getVerbPhraseForCanonicalKey,
} from "../../../shared/utils/exerciseLibraryAdapter";

const benchPressPluralLabel = getPluralDisplayNameForCanonicalKey("bench_press");
const benchPressVerbPhrase = getVerbPhraseForCanonicalKey("bench_press");
const dumbbellRowPluralLabel = getPluralDisplayNameForCanonicalKey("dumbbell_row");
const dumbbellRowVerbPhrase = getVerbPhraseForCanonicalKey("dumbbell_row");
const deadliftPluralLabel = getPluralDisplayNameForCanonicalKey("deadlift");
const deadliftVerbPhrase = getVerbPhraseForCanonicalKey("deadlift");

export const onboardingConfig = {
  id: "liftlogic-onboarding-v1",
  version: 1,
  steps: [
    {
      id: "onboarding_mode",
      section: "Plan",
      type: "single_select",
      title: "How do you want to choose your workout plan?",
      body: "We can recommend a plan from your answers, or you can browse the plan library and choose one yourself.",
      field: "onboardingMode",
      options: [
        {
          label: "Help me choose a plan",
          value: "guided",
          description: "Answer a few questions and we will recommend the best match.",
        },
        {
          label: "Browse workout plans",
          value: "browse",
          description: "Look through the plan library now and pick the one you want.",
        },
      ],
      required: true,
      showIf: {
        field: "onboardingMode",
        equals: "guided",
      },
    },
    {
      id: "workout_template_browser",
      section: "Plan",
      type: "workout_template_browser",
      title: "Choose a workout plan",
      body: "You can change this later from the review screen. We will still ask a few questions afterward to personalize weights and equipment.",
      field: "selectedWorkoutTemplateId",
      required: true,
      showIf: {
        field: "onboardingMode",
        equals: "browse",
      },
    },
    {
      id: "goal",
      section: "Goals",
      type: "single_select",
      title: "What is your main goal right now?",
      body: "Muscle growth usually means more total training volume, moderate-to-higher reps, and steady progression. Strength usually means heavier compound lifts, lower reps, longer rest, and more practice with big movements.",
      field: "goal",
      options: [
        {
          label: "Build muscle",
          value: "hypertrophy",
          description: "Prioritize size, training volume, and controlled reps.",
        },
        {
          label: "Build strength",
          value: "strength",
          description: "Prioritize heavier compound lifts, lower reps, and longer rest.",
        },
        {
          label: "Build muscle and strength",
          value: "hybrid",
          description: "Blend strength practice with enough volume to grow.",
        },
      ],
      required: true,
    },
    {
      id: "goal_priority",
      section: "Goals",
      type: "single_select",
      title: "Which should we prioritize first?",
      field: "goalPriority",
      options: [
        { label: "Muscle growth", value: "hypertrophy" },
        { label: "Strength gain", value: "strength" },
      ],
      required: true,
      showIf: {
        all: [
          {
            field: "onboardingMode",
            equals: "guided",
          },
          {
            field: "goal",
            equals: "hybrid",
          },
        ],
      },
    },
    {
      id: "experience",
      section: "Profile",
      type: "single_select",
      title: "How would you describe your lifting experience?",
      field: "experienceLevel",
      options: [
        {
          label: "Brand new to lifting",
          value: "beginner",
          description: "First time working out, lifted before but unsure what exercises do, or want clear guidance.",
        },
        {
          label: "Some experience",
          value: "intermediate",
          description: "More than 5 years of lifting, comfortable with equipment, and able to make small plan edits.",
        },
        {
          label: "Very experienced",
          value: "advanced",
          description: "More than 10 years training consistently, built your own plans, and comfortable in any gym.",
        },
      ],
      required: true,
    },
    {
      id: "gender",
      section: "Profile",
      type: "single_select",
      title: "What is your gender?",
      body: "This helps us keep starting recommendations reasonable. Most personalization still comes from your experience, schedule, and the weights you report.",
      field: "gender",
      options: [
        { label: "Male", value: "male" },
        { label: "Female", value: "female" },
      ],
      required: true,
    },
    {
      id: "age_range",
      section: "Profile",
      type: "single_select",
      title: "What is your age range?",
      body: "Age helps us adjust how conservative the starting plan should be, especially for younger lifters learning movement quality and older lifters managing recovery.",
      field: "ageRange",
      options: [
        { label: "7-15", value: "7_15" },
        { label: "16-18", value: "16_18" },
        { label: "19-29", value: "19_29" },
        { label: "30-39", value: "30_39" },
        { label: "40-49", value: "40_49" },
        { label: "50+", value: "50_plus" },
      ],
      required: true,
    },
    {
      id: "equipment",
      section: "Profile",
      type: "single_select",
      title: "What equipment do you have access to?",
      field: "equipmentAccess",
      options: [
        {
          label: "Full gym",
          value: "full_gym",
          description: "Squat racks, barbells, dumbbells, benches, machines, cables, and cardio equipment.",
        },
        {
          label: "Home gym",
          value: "home_gym",
          description: "A rack or stands, barbell and plates, bench, dumbbells, bands, and possibly a pulley or cable setup.",
        },
        {
          label: "Dumbbells only",
          value: "dumbbells_only",
          description: "Adjustable or fixed dumbbells with enough room for presses, rows, lunges, and Romanian deadlifts.",
        },
        {
          label: "Basic equipment",
          value: "basic_equipment",
          description: "Bodyweight space, resistance bands, a pull-up bar, a bench, or a small mix of light equipment.",
        },
      ],
      required: true,
    },
    {
      id: "training_days",
      section: "Schedule",
      type: "single_select",
      title: "How many days per week can you work out?",
      body: "This is one of the biggest factors in choosing your plan. We will prefer plans that fit your real week instead of giving you more days than you can recover from or complete.",
      field: "availableTrainingDays",
      options: [
        { label: "1 day", value: 1 },
        { label: "2 days", value: 2 },
        { label: "3 days", value: 3 },
        { label: "4 days", value: 4 },
        { label: "5 days", value: 5 },
        { label: "6 days", value: 6 },
      ],
      required: true,
    },
    {
      id: "units",
      section: "Profile",
      type: "single_select",
      title: "Which unit do you want to use?",
      field: "weightUnit",
      options: [
        { label: "Pounds (lb)", value: "lb" },
        { label: "Kilograms (kg)", value: "kg" },
      ],
      required: true,
    },
    {
      id: "body_weight",
      section: "Profile",
      type: "number",
      title: "What is your current body weight?",
      field: "bodyWeight",
      required: false,
      min: 0,
      max: 1000,
    },
    {
      id: "core_lifts_intro",
      section: "Starting Weights",
      type: "info",
      title: "Let’s set your starting weights",
      body: "We’ll ask about a few core exercises. If you’re unsure, no problem — we’ll start conservatively and adjust from your first workouts.",
    },
  
    {
      id: "bench_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: `Have you done ${benchPressPluralLabel} before?`,
      field: "benchPress.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym"],
      },
    },
    {
      id: "bench_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: `Do you know a weight you can ${benchPressVerbPhrase} with good form for about 5–8 reps?`,
      field: "benchPress.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "benchPress.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "bench_weight",
      section: "Starting Weights",
      type: "number",
      title: `What weight can you ${benchPressVerbPhrase} with good form for about 5–8 reps?`,
      field: "benchPress.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "benchPress.knowsWorkingWeight", equals: true },
        ],
      },
    },
    {
      id: "bench_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "benchPress.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "benchPress.knowsWorkingWeight", equals: true },
        ],
      },
    },
    {
      id: "bench_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "benchPress.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "benchPress.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "dumbbell_row_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: `Have you done ${dumbbellRowPluralLabel} before?`,
      field: "dumbbellRow.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym", "dumbbells_only", "basic_equipment"],
      },
    },
    {
      id: "dumbbell_row_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: `Do you know a weight you can ${dumbbellRowVerbPhrase} with good form for about 5–8 reps?`,
      field: "dumbbellRow.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          {
            field: "equipmentAccess",
            in: ["full_gym", "home_gym", "dumbbells_only", "basic_equipment"],
          },
          { field: "dumbbellRow.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "dumbbell_row_weight",
      section: "Starting Weights",
      type: "number",
      title: `What weight can you ${dumbbellRowVerbPhrase} with good form for about 5–8 reps?`,
      field: "dumbbellRow.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        field: "dumbbellRow.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "dumbbell_row_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "dumbbellRow.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        field: "dumbbellRow.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "dumbbell_row_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "dumbbellRow.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "dumbbellRow.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "squat_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: "Have you done Squats before?",
      field: "squat.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym"],
      },
    },
    {
      id: "squat_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: "Do you know a weight you can squat with good form for about 5–8 reps?",
      field: "squat.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "squat.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "squat_weight",
      section: "Starting Weights",
      type: "number",
      title: "What weight can you squat with good form for about 5–8 reps?",
      field: "squat.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        field: "squat.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "squat_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "squat.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        field: "squat.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "squat_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "squat.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "squat.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "barbell_deadlift_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: `Have you done ${deadliftPluralLabel} before?`,
      field: "barbellDeadlift.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym"],
      },
    },
    {
      id: "barbell_deadlift_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: `Do you know a weight you can ${deadliftVerbPhrase} with good form for about 5–8 reps?`,
      field: "barbellDeadlift.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "barbellDeadlift.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "barbell_deadlift_weight",
      section: "Starting Weights",
      type: "number",
      title: `What weight can you ${deadliftVerbPhrase} with good form for about 5–8 reps?`,
      field: "barbellDeadlift.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        field: "barbellDeadlift.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "barbell_deadlift_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "barbellDeadlift.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        field: "barbellDeadlift.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "barbell_deadlift_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "barbellDeadlift.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "barbellDeadlift.knowsWorkingWeight",
        equals: true,
      },
    },
  ],
};
