import {
  getPluralDisplayNameForCanonicalKey,
  getVerbPhraseForCanonicalKey,
} from "../../../shared/utils/exerciseLibraryAdapter";

const benchPressPluralLabel = getPluralDisplayNameForCanonicalKey("bench_press");
const benchPressVerbPhrase = getVerbPhraseForCanonicalKey("bench_press");
const dumbbellRowPluralLabel = getPluralDisplayNameForCanonicalKey("dumbbell_row");
const dumbbellRowVerbPhrase = getVerbPhraseForCanonicalKey("dumbbell_row");
const deadliftPluralLabel = getPluralDisplayNameForCanonicalKey("deadlift");
const deadliftVerbPhrase = getVerbPhraseForCanonicalKey("deadlift");

export const onboardingConfig = {
  id: "liftlogic-onboarding-v1",
  version: 1,
  steps: [
    {
      id: "onboarding_mode",
      section: "Plan",
      type: "single_select",
      title: "How do you want to choose your workout plan?",
      body: "We can recommend a plan from your answers, or you can browse the plan library and choose one yourself.",
      field: "onboardingMode",
      options: [
        {
          label: "Help me choose a plan",
          value: "guided",
          description: "Answer a few questions and we will recommend the best match.",
        },
        {
          label: "Browse workout plans",
          value: "browse",
          description: "Look through the plan library now and pick the one you want.",
        },
      ],
      required: true,
    },
    {
      id: "workout_template_browser",
      section: "Plan",
      type: "workout_template_browser",
      title: "Choose a workout plan",
      body: "You can change this later from the review screen. We will still ask a few questions afterward to personalize weights and equipment.",
      field: "selectedWorkoutTemplateId",
      required: true,
      showIf: {
        field: "onboardingMode",
        equals: "browse",
      },
    },
    {
      id: "goal",
      section: "Goals",
      type: "single_select",
      title: "What is your main goal right now?",
      body: "Muscle growth usually means more total training volume, moderate-to-higher reps, and steady progression. Strength usually means heavier compound lifts, lower reps, longer rest, and more practice with big movements.",
      field: "goal",
      options: [
        {
          label: "Build muscle",
          value: "hypertrophy",
          description: "Prioritize size, training volume, and controlled reps.",
        },
        {
          label: "Build strength",
          value: "strength",
          description: "Prioritize heavier compound lifts, lower reps, and longer rest.",
        },
        {
          label: "Build muscle and strength",
          value: "hybrid",
          description: "Blend strength practice with enough volume to grow.",
        },
      ],
      required: true,
    },
    {
      id: "goal_priority",
      section: "Goals",
      type: "single_select",
      title: "Which should we prioritize first?",
      field: "goalPriority",
      options: [
        { label: "Muscle growth", value: "hypertrophy" },
        { label: "Strength gain", value: "strength" },
      ],
      required: true,
      showIf: {
        all: [
          {
            field: "onboardingMode",
            equals: "guided",
          },
          {
            field: "goal",
            equals: "hybrid",
          },
        ],
      },
    },
    {
      id: "body_composition_goal",
      section: "Goals",
      type: "single_select",
      title: "What body composition outcome matters most?",
      body: "This helps us choose the right balance of lifting volume, recovery, and conditioning without changing your main training goal.",
      field: "bodyCompositionGoal",
      options: [
        {
          label: "Lose fat",
          value: "lose_fat",
          description: "Prefer plans that are realistic to recover from while supporting consistency.",
        },
        {
          label: "Maintain weight",
          value: "maintain_weight",
          description: "Keep the plan balanced around steady training and recovery.",
        },
        {
          label: "Gain muscle",
          value: "gain_muscle",
          description: "Favor enough weekly volume to support muscle growth.",
        },
        {
          label: "Not sure yet",
          value: "not_sure",
          description: "We will keep the recommendation general and easy to adjust later.",
        },
      ],
      required: true,
    },
    {
      id: "experience",
      section: "Profile",
      type: "single_select",
      title: "How would you describe your lifting experience?",
      field: "experienceLevel",
      options: [
        {
          label: "Brand new to lifting",
          value: "beginner",
          description: "First time working out, lifted before but unsure what exercises do, or want clear guidance.",
        },
        {
          label: "Some experience",
          value: "intermediate",
          description: "More than 5 years of lifting, comfortable with equipment, and able to make small plan edits.",
        },
        {
          label: "Very experienced",
          value: "advanced",
          description: "More than 10 years training consistently, built your own plans, and comfortable in any gym.",
        },
      ],
      required: true,
    },
    {
      id: "recent_training_consistency",
      section: "Profile",
      type: "single_select",
      title: "How consistently have you trained lately?",
      body: "This tells us how much weekly volume is realistic right now. Someone returning after a break may need a different starting plan than someone training consistently.",
      field: "recentTrainingConsistency",
      options: [
        {
          label: "Brand new",
          value: "brand_new",
          description: "You are starting from scratch or have not lifted regularly before.",
        },
        {
          label: "Inconsistent lately",
          value: "inconsistent",
          description: "You have trained before, but your routine has been off and on.",
        },
        {
          label: "1-2 days per week",
          value: "one_two_days",
          description: "You have been getting some sessions in most weeks.",
        },
        {
          label: "3-4 days per week",
          value: "three_four_days",
          description: "You have a steady rhythm and can handle moderate weekly volume.",
        },
        {
          label: "5+ days per week",
          value: "five_plus_days",
          description: "You are already training frequently and recovering well.",
        },
      ],
      required: true,
    },
    {
      id: "gender",
      section: "Profile",
      type: "single_select",
      title: "What is your gender?",
      body: "This helps us keep starting recommendations reasonable. Most personalization still comes from your experience, schedule, and the weights you report.",
      field: "gender",
      options: [
        { label: "Male", value: "male" },
        { label: "Female", value: "female" },
      ],
      required: true,
    },
    {
      id: "age_range",
      section: "Profile",
      type: "single_select",
      title: "What is your age range?",
      body: "Age helps us adjust how conservative the starting plan should be, especially for younger lifters learning movement quality and older lifters managing recovery.",
      field: "ageRange",
      options: [
        { label: "7-15", value: "7_15" },
        { label: "16-18", value: "16_18" },
        { label: "19-29", value: "19_29" },
        { label: "30-39", value: "30_39" },
        { label: "40-49", value: "40_49" },
        { label: "50+", value: "50_plus" },
      ],
      required: true,
    },
    {
      id: "equipment",
      section: "Profile",
      type: "single_select",
      title: "What equipment do you have access to?",
      field: "equipmentAccess",
      options: [
        {
          label: "Full gym",
          value: "full_gym",
          description: "Squat racks, barbells, dumbbells, benches, machines, cables, and cardio equipment.",
        },
        {
          label: "Home gym",
          value: "home_gym",
          description: "A rack or stands, barbell and plates, bench, dumbbells, bands, and possibly a pulley or cable setup.",
        },
        {
          label: "Dumbbells only",
          value: "dumbbells_only",
          description: "Adjustable or fixed dumbbells with enough room for presses, rows, lunges, and Romanian deadlifts.",
        },
        {
          label: "Basic equipment",
          value: "basic_equipment",
          description: "Bodyweight space, resistance bands, a pull-up bar, a bench, or a small mix of light equipment.",
        },
      ],
      required: true,
    },
    {
      id: "available_equipment",
      section: "Profile",
      type: "equipment_inventory",
      title: "Confirm your equipment",
      body: "Start with the preset you picked, then fine-tune the exact equipment you can use. We will use this to choose better exercises and substitutions.",
      field: "availableEquipment",
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym", "dumbbells_only", "basic_equipment"],
      },
    },
    {
      id: "training_days",
      section: "Schedule",
      type: "single_select",
      title: "How many days per week can you work out?",
      body: "This is one of the biggest factors in choosing your plan. We will prefer plans that fit your real week instead of giving you more days than you can recover from or complete.",
      field: "availableTrainingDays",
      options: [
        { label: "1 day", value: 1 },
        { label: "2 days", value: 2 },
        { label: "3 days", value: 3 },
        { label: "4 days", value: 4 },
        { label: "5 days", value: 5 },
        { label: "6 days", value: 6 },
      ],
      required: true,
    },
    {
      id: "session_length",
      section: "Schedule",
      type: "single_select",
      title: "How long can most workouts be?",
      body: "We will avoid recommending plans that technically fit your week but regularly take longer than you can train.",
      field: "sessionLength",
      options: [
        {
          label: "20-30 minutes",
          value: "20_30",
          description: "Best for shorter, focused sessions with fewer exercises.",
        },
        {
          label: "30-45 minutes",
          value: "30_45",
          description: "Good for efficient full-body or split workouts.",
        },
        {
          label: "45-60 minutes",
          value: "45_60",
          description: "Enough time for compounds plus accessory work.",
        },
        {
          label: "60-90 minutes",
          value: "60_90",
          description: "Best for higher-volume plans and longer rest periods.",
        },
      ],
      required: true,
    },
    {
      id: "units",
      section: "Profile",
      type: "single_select",
      title: "Which unit do you want to use?",
      field: "weightUnit",
      options: [
        { label: "Pounds (lb)", value: "lb" },
        { label: "Kilograms (kg)", value: "kg" },
      ],
      required: true,
    },
    {
      id: "body_weight",
      section: "Profile",
      type: "number",
      title: "What is your current body weight?",
      body: "Optional. This helps us scale bodyweight movements and keep starting recommendations reasonable. It is used as general guidance only.",
      field: "bodyWeight",
      required: false,
      min: 0,
      max: 1000,
    },
    {
      id: "height",
      section: "Profile",
      type: "number",
      title: "What is your height in inches?",
      body: "Optional. For example, 5'10\" is 70 inches. We use this only as broad context with body weight, never as a limit.",
      field: "heightInches",
      required: false,
      min: 36,
      max: 96,
    },
    {
      id: "recommendation_fine_tuning",
      section: "Preferences",
      type: "single_select",
      title: "Want to fine-tune your recommendation?",
      body: "You can tell us about movements you are unsure about, joints you want to be careful with, or exercises you strongly dislike. This is optional and you can update it later.",
      field: "wantsRecommendationFineTuning",
      options: [
        {
          label: "Skip for now",
          value: false,
          description: "Keep the recommendation simple and continue to starting weights.",
        },
        {
          label: "Fine-tune it",
          value: true,
          description: "Add a few preferences so LiftLogic can guide future plan updates.",
        },
      ],
      required: true,
    },
    {
      id: "movement_confidence",
      section: "Preferences",
      type: "single_select",
      title: "How confident do you feel with gym movements?",
      body: "This helps us decide how much form-first guidance and exercise conservatism to use.",
      field: "movementConfidence",
      options: [
        {
          label: "I need guidance",
          value: "need_guidance",
          description: "Prioritize simpler movements and clearer exercise coaching.",
        },
        {
          label: "Comfortable with basics",
          value: "comfortable_basics",
          description: "Use common lifts, but avoid overly technical movements by default.",
        },
        {
          label: "Very confident",
          value: "very_confident",
          description: "You are comfortable learning and performing most gym exercises.",
        },
      ],
      required: false,
      showIf: {
        field: "wantsRecommendationFineTuning",
        equals: true,
      },
    },
    {
      id: "joint_concerns",
      section: "Preferences",
      type: "multi_select",
      title: "Any joints or areas you want to be careful with?",
      body: "Select anything that needs extra attention. This will become guidance, not a hard limit.",
      field: "jointConcerns",
      options: [
        { label: "Shoulders", value: "shoulders" },
        { label: "Elbows", value: "elbows" },
        { label: "Wrists", value: "wrists" },
        { label: "Lower back", value: "lower_back" },
        { label: "Hips", value: "hips" },
        { label: "Knees", value: "knees" },
        { label: "Ankles", value: "ankles" },
      ],
      required: false,
      showIf: {
        field: "wantsRecommendationFineTuning",
        equals: true,
      },
    },
    {
      id: "disliked_exercises",
      section: "Preferences",
      type: "multi_select",
      title: "Any exercises you strongly dislike?",
      body: "A plan you enjoy is easier to follow. Pick only movements you would rather avoid when good alternatives exist.",
      field: "dislikedExerciseIds",
      options: [
        {
          label: "Back Squat",
          value: "back_squat",
          description: "Heavy barbell squats or similar loaded squat patterns.",
        },
        {
          label: "Deadlift",
          value: "deadlift",
          description: "Heavy pulls from the floor or similar hinge patterns.",
        },
        {
          label: "Overhead Press",
          value: "standing_overhead_press",
          description: "Pressing weight overhead with a barbell or dumbbells.",
        },
        {
          label: "Pull-Up",
          value: "pull_up",
          description: "Bodyweight vertical pulling movements.",
        },
        {
          label: "Lunges",
          value: "dumbbell_lunge",
          description: "Split-stance or stepping leg exercises.",
        },
        {
          label: "Leg Press",
          value: "leg_press",
          description: "Machine-based heavy leg pressing.",
        },
        {
          label: "Hip Thrust",
          value: "barbell_hip_thrust",
          description: "Loaded glute bridge or hip thrust movements.",
        },
        {
          label: "Burpees",
          value: "burpee",
          description: "High-effort bodyweight conditioning movements.",
        },
      ],
      required: false,
      showIf: {
        field: "wantsRecommendationFineTuning",
        equals: true,
      },
    },
    {
      id: "core_lifts_intro",
      section: "Starting Weights",
      type: "info",
      title: "Let’s set your starting weights",
      body: "We’ll ask about a few core exercises. If you’re unsure, no problem — we’ll start conservatively and adjust from your first workouts.",
    },
  
    {
      id: "bench_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: `Have you done ${benchPressPluralLabel} before?`,
      field: "benchPress.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym"],
      },
    },
    {
      id: "bench_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: `Do you know a weight you can ${benchPressVerbPhrase} with good form for about 5–8 reps?`,
      field: "benchPress.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "benchPress.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "bench_weight",
      section: "Starting Weights",
      type: "number",
      title: `What weight can you ${benchPressVerbPhrase} with good form for about 5–8 reps?`,
      field: "benchPress.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "benchPress.knowsWorkingWeight", equals: true },
        ],
      },
    },
    {
      id: "bench_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "benchPress.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "benchPress.knowsWorkingWeight", equals: true },
        ],
      },
    },
    {
      id: "bench_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "benchPress.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "benchPress.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "dumbbell_row_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: `Have you done ${dumbbellRowPluralLabel} before?`,
      field: "dumbbellRow.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym", "dumbbells_only", "basic_equipment"],
      },
    },
    {
      id: "dumbbell_row_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: `Do you know a weight you can ${dumbbellRowVerbPhrase} with good form for about 5–8 reps?`,
      field: "dumbbellRow.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          {
            field: "equipmentAccess",
            in: ["full_gym", "home_gym", "dumbbells_only", "basic_equipment"],
          },
          { field: "dumbbellRow.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "dumbbell_row_weight",
      section: "Starting Weights",
      type: "number",
      title: `What weight can you ${dumbbellRowVerbPhrase} with good form for about 5–8 reps?`,
      field: "dumbbellRow.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        field: "dumbbellRow.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "dumbbell_row_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "dumbbellRow.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        field: "dumbbellRow.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "dumbbell_row_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "dumbbellRow.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "dumbbellRow.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "squat_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: "Have you done Squats before?",
      field: "squat.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym"],
      },
    },
    {
      id: "squat_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: "Do you know a weight you can squat with good form for about 5–8 reps?",
      field: "squat.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "squat.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "squat_weight",
      section: "Starting Weights",
      type: "number",
      title: "What weight can you squat with good form for about 5–8 reps?",
      field: "squat.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        field: "squat.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "squat_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "squat.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        field: "squat.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "squat_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "squat.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "squat.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "barbell_deadlift_familiarity",
      section: "Starting Weights",
      type: "single_select",
      title: `Have you done ${deadliftPluralLabel} before?`,
      field: "barbellDeadlift.familiarity",
      options: [
        { label: "Never", value: "never" },
        { label: "A little", value: "some" },
        { label: "Often", value: "often" },
      ],
      required: true,
      showIf: {
        field: "equipmentAccess",
        in: ["full_gym", "home_gym"],
      },
    },
    {
      id: "barbell_deadlift_knows_weight",
      section: "Starting Weights",
      type: "single_select",
      title: `Do you know a weight you can ${deadliftVerbPhrase} with good form for about 5–8 reps?`,
      field: "barbellDeadlift.knowsWorkingWeight",
      options: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
      required: true,
      showIf: {
        all: [
          { field: "equipmentAccess", in: ["full_gym", "home_gym"] },
          { field: "barbellDeadlift.familiarity", in: ["some", "often"] },
        ],
      },
    },
    {
      id: "barbell_deadlift_weight",
      section: "Starting Weights",
      type: "number",
      title: `What weight can you ${deadliftVerbPhrase} with good form for about 5–8 reps?`,
      field: "barbellDeadlift.estimatedWeight",
      required: true,
      min: 0,
      max: 2000,
      showIf: {
        field: "barbellDeadlift.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "barbell_deadlift_reps",
      section: "Starting Weights",
      type: "number",
      title: "How many clean reps can you do with that weight before form starts to break down?",
      field: "barbellDeadlift.estimatedReps",
      required: true,
      min: 1,
      max: 30,
      showIf: {
        field: "barbellDeadlift.knowsWorkingWeight",
        equals: true,
      },
    },
    {
      id: "barbell_deadlift_confidence",
      section: "Starting Weights",
      type: "single_select",
      title: "How confident are you in that estimate?",
      field: "barbellDeadlift.confidence",
      options: [
        { label: "Very confident", value: "high" },
        { label: "Somewhat confident", value: "medium" },
        { label: "Not very confident", value: "low" },
      ],
      required: true,
      showIf: {
        field: "barbellDeadlift.knowsWorkingWeight",
        equals: true,
      },
    },
  ],
};
